### ISSUE TITLE
Macos starting error

### ISSUE THREAD

**Issue by bycko** [shine-jayakumar/insta-likecom-bot#117]
Hello, im trying to start it like on example but for every single command im getting this

`Traceback (most recent call last):
  File "/insta-likecom-bot/ilcbot.py", line 14, in <module>
    from modules.insta import Insta
  File "/insta-likecom-bot/modules/__init__.py", line 5, in <module>
    from . import insta
  File "/insta-likecom-bot/modules/insta.py", line 47, in <module>
    from modules.locators import (
  File "/insta-likecom-bot/modules/locators.py", line 50, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'modules.locators.SaveLoginLocators'> for field save_login is not allowed: use default_factory
`

**Comment by bycko** [comment]
Downgraded to python 3.10 and problem solved
