### ISSUE TITLE
Locator Error on v.05

### ISSUE THREAD

**Issue by digitizesuccess** [shine-jayakumar/insta-likecom-bot#119]
I am unsure of how to troubleshoot this. Has anyone come across this error?

`/usr/local/bin/python3` ilcbot.py -u xxx -p xxxx -t 'xxx' -ff -np 1 -nc -fa 200 --delay 2,20 --limits /Users/xxx/insta-likecom-bot/limits.json --ignoretags /Users/xxx/insta-likecom-bot/Ignorelist.txt
Traceback (most recent call last):
  File "/Users/xxx/insta-likecom-bot/ilcbot.py", line 14, in <module>
    from modules.insta import Insta
  File "/Users/xxx/insta-likecom-bot/modules/__init__.py", line 5, in <module>
    from . import insta
  File "/Users/xxx/insta-likecom-bot/modules/insta.py", line 47, in <module>
    from modules.locators import (
  File "/Users/xxx/insta-likecom-bot/modules/locators.py", line 50, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'modules.locators.SaveLoginLocators'> for field save_login is not allowed: use `default_factory`

**Comment by shine-jayakumar** [comment]
Duplicate issue. This issue is already raised #118

**Comment by shine-jayakumar** [comment]
Issue already raised #118

**Comment by shine-jayakumar** [comment]
This issue has been recognized and will be fixed soon.

**Comment by shine-jayakumar** [comment]
Issue fixed in latest version. The fix is compatible with newer versions as well.
