### ISSUE TITLE
Emojis do not work in comments | Avoid same user from explore page

### ISSUE THREAD

**Issue by Skuwwy** [shine-jayakumar/insta-likecom-bot#51]
Hello, loving all the new updates. The bot works flawlessly! I have one issue and one suggestion.

I've noticed that the bot throws an error when a comment from the list is only emojis. For example "😍👌".

Here's the error:
```
Traceback (most recent call last):
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Legion\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 92-94: character maps to <undefined>
Call stack:
  File "D:\InstaBot 2\insta-likecom-bot\instalikecombot.py", line 418, in <module>
    logger.info(f'[target: {target}] Commented: {random_comment}')
Message: '[target: #midjourney] Commented: 😍👌👌'
Arguments: ()
```

Can this be fixed?

Also, is there a way to prevent the bot from commenting on the same user more than once when exploring hashtags?

**Comment by shine-jayakumar** [comment]
I am glad you find it useful. 
- Issue with emojis has been addressed earlier. The underlying driver throws this error when it encounters certain emojis. It has to do with encoding issues when sending text (with certain emjois) to a textarea on Chrome. Firefox doesn't have this problem, however, I've put  a hold on development for Firefox for some time. I will revist the encoding issue with emjois soon.

- **Not commenting on the same user more than once** - this would be a good addition

- **Avoid interacting with posts containing certain tags** - currently the --matchtag, --matchtagnum can be used to filter out posts based on the tags. Although, adding this option seems totally logical.

Thank you for your kind words and suggestions. Keep them coming.

**Comment by Skuwwy** [comment]
Thanks @shine-jayakumar , looking forward to it!

Is there an existing function to simply let the bot go through my home feed and like a predefined number of posts? (Except sponsored)

**Comment by YoussefEssalhi** [comment]
@shine-jayakumar , Maybe this code will help solve the emoji problem :

```py
text_element = driver_trader.find_element_by_xpath('xpath')
text = '⚪📢😆'

driver.execute_script("arguments[0].innerHTML = '{}'".format(text),text_element)
text_element.send_keys('.')
text_element.send_keys(Keys.BACKSPACE)
```

Reference : https://stackoverflow.com/questions/51706256/sending-emojis-with-seleniums-send-keys
