### ISSUE TITLE
strarting the scripts gives modules.instafunc error

### ISSUE THREAD

**Issue by name-in-use** [shine-jayakumar/insta-likecom-bot#93]
PS C:\Users\Xrhst\Desktop\AI OFM\insta-likecom-bot-master\insta-likecom-bot-master> ./ilcbot.py
PS C:\Users\Xrhst\Desktop\AI OFM\insta-likecom-bot-master\insta-likecom-bot-master> python ilcbot.py
Traceback (most recent call last):
  File "C:\Users\Xrhst\Desktop\AI OFM\insta-likecom-bot-master\insta-likecom-bot-master\ilcbot.py", line 15, in <module>
    from modules.instafunc import *
  File "C:\Users\Xrhst\Desktop\AI OFM\insta-likecom-bot-master\insta-likecom-bot-master\modules\instafunc.py", line 52, in <module>
    logger = AppLogger(__name__).getlogger()
  File "C:\Users\Xrhst\Desktop\AI OFM\insta-likecom-bot-master\insta-likecom-bot-master\modules\applogger.py", line 35, in __init__
    file_handler = TimedRotatingFileHandler(logfname, when='midnight')
  File "C:\Users\Xrhst\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "C:\Users\Xrhst\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "C:\Users\Xrhst\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Xrhst\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Xrhst\\Desktop\\AI OFM\\insta-likecom-bot-master\\insta-likecom-bot-master\\logs\\instalikecombot_2023_10_12.log'

**Comment by shine-jayakumar** [comment]
Create a folder named `logs` and run the script again

**Comment by name-in-use** [comment]
I see that you havent code part for accepting cookies when instagram page opens. and gives error

**Comment by shine-jayakumar** [comment]
> I see that you havent code part for accepting cookies when instagram page opens...After opens instagram page immediately closes with error. how we should handle that

I haven't had the need to explicitly handle cookies. Let me know the error log so I can see the error.
